name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_image_picker_view:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
